name: meshresq
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  # Architecture & State Management
  flutter_riverpod: ^2.5.1

  # Firebase Authentication
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1

  # Offline Storage & Identity
  hive_flutter: ^1.1.0
  uuid: ^4.3.3
  http: ^1.2.2

  # Hardware & Permissions
  permission_handler: ^11.3.1
  geolocator: ^11.0.0

  # UI & Design System
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.1.0
  glassmorphism: ^3.0.0
  smooth_page_indicator: ^1.1.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true